export const ADD_QUESTION = 'ADD_QUESTION';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const GET_QUESTION = 'GET_QUESTION';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

/* ASYNC REQUESTS */

export const ASYNC_REQUEST = 'ASYNC_REQUEST';
export const ASYNC_SUCCESS = 'ASYNC_SUCCESS';
export const ASYNC_ERROR = 'ASYNC_ERROR';
